### ISSUE TITLE
Is this package maintained?

### ISSUE THREAD

**Issue by ghost** [kascote/universal_feed#1]
I've found this package after much trouble with webfeed (specially date time parsing) and so far it's been way better, so thanks for great work you've done here.
But considering what you've said in README and dependencies not being updated, do you have plans for working on this?

**Comment by kascote** [comment]
Hey! Glad to hear that you are using it and you like it!

I was with a lot of work lately and could not work on this library. But I have good news and bad news. The good news is that I resumed work on it this last week! And the bad news is that I'm rewriting much of it. 
The current one has two parsers (Atom and RSS) and then tries to unify both worlds under UniversalFeed and was getting a mess.
The new approach will have only UniversalFeed with a common set of fields. The library's users will need to only work with this entity. 
In resume, I'm working on it now; the next version will be a new beast, and I don't have a time frame for it.

**Comment by ghost** [comment]
Great! Considering it's still pre 1.0 these type of changes are expected. it can actually make conversion to domain types in apps easier for us as well, since there would be only one mapping.
I love your comments in code and references to main documentations and RFCs, please keep/improve them.
Also, while you're at it would be nice to improve barrel files. I have to import implementation files for things like RSSItems and RSSChannel which leads to [implementation_imports](https://dart-lang.github.io/linter/lints/implementation_imports.html) (It's a minor nitpick, I know!).
Thanks again

**Comment by kascote** [comment]
we have a new version! 🎉

**Comment by sunderee** [comment]
Thank you! I'm starting to use it right now.

**Comment by Dotnaught** [comment]
Thanks for writing this. I was afraid I would have do try doing so and I don't think I'm up to it :-)
