### ISSUE TITLE
Icon vs. Logo in Atom feed

### ISSUE THREAD

**Issue by d370urn3ur** [kascote/universal_feed#2]
Why is icon ignored in Atom?

lines 61-62 in atom_parser.dart :

```dart
// getElement<String>(root, 'icon', cb: (value) => uf.icon = value);
getElement<XmlElement>(root, 'logo', cb: (element) => uf.image = Image.fromXml(element));
```

The Atom spec allows for both icon and logo (optional). This Polygon feed contains icon but no logo: http://www.polygon.com/rss/index.xml

What is the reasoning behind removing icon from UniversalFeed? I use icons in my app to help identify a channel so having access to that icon would be a great help.

**Comment by kascote** [comment]
That's a very good question! I can't not remember why I left it out, probably an oversight on my part :(

**Comment by kascote** [comment]
`universal_feed` 0.5 released, thanks!
